USE LOCADORA;
GO

SELECT * FROM EMPRESA
SELECT * FROM VEICULO
SELECT * FROM MODELO
SELECT * FROM MARCA
SELECT * FROM CLIENTE
SELECT * FROM ALUGUEL

SELECT DataDevol, nomeCliente, nomeModelo
FROM ALUGUEL
INNER JOIN CLIENTE
ON ALUGUEL.idCliente = CLIENTE.idCliente
INNER JOIN MODELO
ON ALUGUEL.idVeiculo = MODELO.idModelo;
GO

SELECT nomeCliente, DataDevol, nomeModelo 
FROM ALUGUEL
INNER JOIN CLIENTE
ON CLIENTE.idCliente = ALUGUEL.idAluguel
INNER JOIN MODELO
ON ALUGUEL.idVeiculo = MODELO.idModelo
WHERE CLIENTE.nomeCliente = 'João'