--DDL

CREATE DATABASE M_Rental;
GO

USE M_Rental;
GO

CREATE TABLE CLIENTE(
	idCliente SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeCliente VARCHAR(25) NOT NULL,
	sobrenome VARCHAR (25) NOT NULL
);
GO

CREATE TABLE MARCA(
	idMarca SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeMARCA VARCHAR(25) NOT NULL 
);
GO

CREATE TABLE MODELO(
	idModelo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idMarca SMALLINT FOREIGN KEY REFERENCES MARCA(idMarca),
	nomeModelo VARCHAR(25) NOT NULL 
);
GO

CREATE TABLE VEICULO(
	idVeiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo),
	PLACA CHAR(8) NOT NULL UNIQUE
);
GO

CREATE TABLE ALUGUEL(
	idAluguel SMALLINT PRIMARY KEY IDENTITY(1,1),
	idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
	idCliente SMALLINT FOREIGN KEY REFERENCES CLIENTE(idCliente),
	DataDevol DATE NOT NULL
);
GO

SELECT * FROM ALUGUEL;

--incluir data retirada
ALTER TABLE ALUGUEL ADD DataRetirada DATE NOT NULL;